theme: jekyll-theme-hacker
title: [WALCZ O SUPERPOZYCJĘ - Kwantowe Wyzwanie Banku BNP Paribas]
description: [Zostań developerem kwantowym i zdobądź płatny staż w Banku BNP Paribas]
github:
  is_project_page: false
